<?php

use Illuminate\Database\Seeder;
use App\Repositories\EntityParamsRepository;
use App\Models\EntityParam;

class EntityParamsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $repo    = resolve(EntityParamsRepository::class);
        $data = [
            [
                'id'  => 1,
                'parent_id' => null,
                'entity_id' => 1,
                'name' => 'Главное меню',
                'description' => 'Главное верхнее меню',
                'parameter' => 'menu.main',
            ],
            [
                'id'  => 2,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Доступ',
                'description' => 'Главное верхнее меню - Доступ',
                'parameter' => 'menu.main.access',
            ],
            [
                'id'  => 3,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Справочники',
                'description' => 'Главное верхнее меню - Справочники',
                'parameter' => 'menu.main.dictionaries',
            ],
            [
                'id'  => 4,
                'parent_id' => 2,
                'entity_id' => 1,
                'name' => 'Пользователи',
                'description' => 'Пользователи',
                'parameter' => 'menu.main.access.users',
            ],
            [
                'id'  => 5,
                'parent_id' => 2,
                'entity_id' => 1,
                'name' => 'Роли',
                'description' => 'Роли',
                'parameter' => 'menu.main.access.role_groups',
            ],
            [
                'id'  => 6,
                'parent_id' => 2,
                'entity_id' => 1,
                'name' => 'Структура разделов для доступа',
                'description' => 'Структура разделов для доступа',
                'parameter' => 'menu.main.access.entities',
            ],
            [
                'id'  => 7,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Валюта',
                'description' => 'Валюта',
                'parameter' => 'menu.main.dictionaries.currency',
            ],
            [
                'id'  => 8,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Выгрузки',
                'description' => 'Выгрузки',
                'parameter' => 'menu.main.dictionaries.unloads',
            ],
            [
                'id'  => 9,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Гео',
                'description' => 'Гео',
                'parameter' => 'menu.main.dictionaries.geos',
            ],
            [
                'id'  => 10,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Звонки',
                'description' => 'Звонки',
                'parameter' => 'menu.main.dictionaries.calls',
            ],
            [
                'id'  => 11,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Источники трафика',
                'description' => 'Источники трафика',
                'parameter' => 'menu.main.dictionaries.traffics',
            ],
            [
                'id'  => 12,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Категории продуктов',
                'description' => 'Категории продуктов',
                'parameter' => 'menu.main.dictionaries.product_category',
            ],
            [
                'id'  => 13,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Категории проектов',
                'description' => 'Категории проектов',
                'parameter' => 'menu.main.dictionaries.project_category',
            ],
            [
                'id'  => 14,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Колл-центры',
                'description' => 'Колл-центры',
                'parameter' => 'menu.main.dictionaries.call_center',
            ],
            [
                'id'  => 15,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Продукты',
                'description' => 'Продукты',
                'parameter' => 'menu.main.dictionaries.products',
            ],
            [
                'id'  => 16,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Проекты',
                'description' => 'Проекты',
                'parameter' => 'menu.main.dictionaries.projects',
            ],
            [
                'id'  => 17,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Типы доставки',
                'description' => 'Типы доставки',
                'parameter' => 'menu.main.dictionaries.delivery_types',
            ],
            [
                'id'  => 18,
                'parent_id' => 4,
                'entity_id' => 1,
                'name' => 'Просмотр огранизаций',
                'description' => 'Просмотр огранизаций',
                'parameter' => 'menu.main.access.users.organizations.view',
            ],
            [
                'id'  => 19,
                'parent_id' => 4,
                'entity_id' => 1,
                'name' => 'Список организаций',
                'description' => 'Список организаций',
                'parameter' => 'menu.main.access.users.organizations.list',
            ],
            [
                'id'  => 20,
                'parent_id' => 4,
                'entity_id' => 1,
                'name' => 'Cоздание организации',
                'description' => 'Cоздание организации',
                'parameter' => 'menu.main.access.users.organizations.create',
            ],
            [
                'id'  => 21,
                'parent_id' => 4,
                'entity_id' => 1,
                'name' => 'Cоздание пользователя',
                'description' => 'Cоздание пользователя',
                'parameter' => 'menu.main.access.users.create',
            ],
            [
                'id'  => 22,
                'parent_id' => 4,
                'entity_id' => 1,
                'name' => 'Просмотр страницы пользователей',
                'description' => 'Просмотр страницы пользователей',
                'parameter' => 'menu.main.access.users.view',
            ],
            [
                'id'  => 23,
                'parent_id' => 4,
                'entity_id' => 1,
                'name' => 'Право на назначение компании',
                'description' => 'Право на назначение компании',
                'parameter' => 'menu.main.access.users.organizations.set_company',
            ],
            [
                'id'  => 24,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Заказы',
                'description' => 'Доступ к разделу заказы',
                'parameter' => 'menu.main.orders'
            ],
            [
                'id'  => 25,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Выгрузки',
                'description' => 'Право на просмотр и редактирование выгрузок',
                'parameter' => 'menu.main.unloads'
            ],
            [
                'id'  => 26,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Просмотр всех доступных заказов',
                'description' => 'Просмотр всех доступных заказов(true - просмотр всех, false - просмотр только своих)',
                'parameter' => 'menu.main.orders.own_only'
            ],
            [
                'id'  => 27,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Редактирование стоимости заказа',
                'description' => 'Блокировать редактирование "Стоимость товара", "Стоимость доставки", "Добавить товар", "Кол-во товара", "Удалить товар", "Копировать товар" ',
                'parameter' => 'menu.main.orders.edit_price'
            ],
            [
                'id'  => 28,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Просмотр трек номера',
                'description' => 'Доступ на просмотр трек номера, если доступа нет, просмотреть трек номер из карточки заказа, а так же, на странице заказов нельзя',
                'parameter' => 'menu.main.orders.view_track_number'
            ],
            [
                'id'  => 29,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Редактирование трек номера',
                'description' => 'Если доступа нет, редактировать поле трек номер нельзя.',
                'parameter' => 'menu.main.orders.edit_track_number'
            ],
            [
                'id'  => 30,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Просмотр номера телефона клиента в заказе',
                'description' => 'Если доступа нет, то поле "номер телефона", "доп номер телефона" должны быть неактивными, номера телефонов забитые в них, должны быть частично скрыты, скрываться должны последние 5 цифр в номере телефона.',
                'parameter' => 'menu.main.orders.view_phone_number'
            ],
            [
                'id'  => 31,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Просмотр записей разговоров с клиентом',
                'description' => 'Если доступа нет, записи в карточке заказа отображаться не должны.',
                'parameter' => 'menu.main.orders.view_call_audio'
            ],
            [
                'id'  => 32,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Запись в чёрный список',
                'description' => 'Если доступа нет, записать клиента в чёрный список будет нельзя, кнопочка записывающяя заказ должна быть скрыта.',
                'parameter' => 'menu.main.orders.edit_black_list'
            ],
            [
                'id'  => 33,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Доступ на просмотр Адресной информации',
                'description' => 'Если доступа нет, то адресная информация в карточке заказа отображаться не должна.',
                'parameter' => 'menu.main.orders.view_address_info'
            ],
            [
                'id'  => 34,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Редактирование менеджера привязанного к заказу',
                'description' => 'Если доступа нет, то селект позволяющий это изменить менеджера должен быть скрыт.',
                'parameter' => 'menu.main.orders.edit_order_manager'
            ],
            [
                'id'  => 35,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Редактирование цены заказа свыше 25%',
                'description' => 'Редактирование цены заказа свыше 25%',
                'parameter' => 'menu.main.orders.edit_price_above_25'
            ],
            [
                'id'  => 36,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Установка апсейлов без ограничений.',
                'description' => 'Установка апсейлов без ограничений.',
                'parameter' => 'menu.main.orders.set_upsales_limitless'
            ],
            [
                'id'  => 67,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Транки',
                'description' => 'Главное верхнее меню - Транки',
                'parameter' => 'menu.main.tranks',
            ],
            [
                'id'  => 68,
                'parent_id' => 67,
                'entity_id' => 1,
                'name' => 'Cоздание',
                'description' => 'Транки - Cоздание',
                'parameter' => 'menu.main.tranks.create',
            ],
            [
                'id'  => 69,
                'parent_id' => 67,
                'entity_id' => 1,
                'name' => 'Редактирование',
                'description' => 'Транки - Редактирование',
                'parameter' => 'menu.main.tranks.edit',
            ],
            [
                'id'  => 70,
                'parent_id' => 67,
                'entity_id' => 1,
                'name' => 'Удаление',
                'description' => 'Транки - Удаление',
                'parameter' => 'menu.main.tranks.delete',
            ],
            [
                'id'  => 71,
                'parent_id' => 67,
                'entity_id' => 1,
                'name' => 'Видеть транки моей компании.',
                'description' => 'Транки - Просмотр.',
                'parameter' => 'menu.main.tranks.show',
            ],
            [
                'id'  => 72,
                'parent_id' => 67,
                'entity_id' => 1,
                'name' => 'Видеть транки других доступных компаний.',
                'description' => 'Транки - Видеть транки других доступных компаний.',
                'parameter' => 'menu.main.tranks.show_other_company_tranks',
            ],
            [
                'id'  => 73,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Сервера',
                'description' => 'Сервера',
                'parameter' => 'menu.main.servers',
            ],
            [
                'id'  => 74,
                'parent_id' => 73,
                'entity_id' => 1,
                'name' => 'Создание',
                'description' => 'Сервера - создание',
                'parameter' => 'menu.main.servers.create',
            ],
            [
                'id'  => 75,
                'parent_id' => 73,
                'entity_id' => 1,
                'name' => 'Редактирование',
                'description' => 'Сервера - редактирование',
                'parameter' => 'menu.main.servers.edit',
            ],
            [
                'id'  => 76,
                'parent_id' => 73,
                'entity_id' => 1,
                'name' => 'Удаление',
                'description' => 'Сервера - Удаление',
                'parameter' => 'menu.main.servers.delete',
            ],
            [
                'id'  => 77,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Отчеты',
                'description' => 'Отчеты',
                'parameter' => 'menu.main.reports',
            ],
            [
                'id'  => 78,
                'parent_id' => 77,
                'entity_id' => 1,
                'name' => 'Отчёт. ЗП Колцентра',
                'description' => 'Отчёт. ЗП Колцентра',
                'parameter' => 'menu.main.reports.call_center_wages',
            ],
            [
                'id'  => 79,
                'parent_id' => 77,
                'entity_id' => 1,
                'name' => 'Отчёт по отделу продаж',
                'description' => 'Отчёт по отделу продаж',
                'parameter' => 'menu.main.reports.sales',
            ],
            [
                'id'  => 80,
                'parent_id' => 77,
                'entity_id' => 1,
                'name' => 'Отчёт общий',
                'description' => 'Отчёт общий',
                'parameter' => 'menu.main.reports.common',
            ],
            [
                'id'  => 81,
                'parent_id' => 77,
                'entity_id' => 1,
                'name' => 'Отчёт по фроду',
                'description' => 'Отчёт по фроду',
                'parameter' => 'menu.main.reports.frod',
            ],
            [
                'id'  => 82,
                'parent_id' => 77,
                'entity_id' => 1,
                'name' => 'Отчёт по бухгалтерии',
                'description' => 'Отчёт по бухгалтерии',
                'parameter' => 'menu.main.reports.accounting',
            ],
            [
                'id'  => 83,
                'parent_id' => 77,
                'entity_id' => 1,
                'name' => 'Отчёт по логистике',
                'description' => 'Отчёт по логистике',
                'parameter' => 'menu.main.reports.logistic',
            ],
            [
                'id'  => 84,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'СМС',
                'description' => 'СМС',
                'parameter' => 'menu.main.dictionaries.sms',
            ],
            [
                'id'  => 85,
                'parent_id' => 84,
                'entity_id' => 1,
                'name' => 'Провайдеры СМС',
                'description' => 'Провайдеры СМС',
                'parameter' => 'menu.main.dictionaries.sms.providers',
            ],
            [
                'id'  => 86,
                'parent_id' => 84,
                'entity_id' => 1,
                'name' => 'Массовая рассылка',
                'description' => 'Массовая рассылка',
                'parameter' => 'menu.main.dictionaries.sms.send',
            ],
             [
                'id'  => 87,
                'parent_id' => 3,
                'entity_id' => 1,
                'name' => 'Статусы',
                'description' => 'Статусы',
                'parameter' => 'menu.main.dictionaries.statuses',
            ],
            [
                'id'  => 88,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Просмотр заказов',
                'description' => 'Просмотр заказов',
                'parameter' => 'menu.main.orders.view'
            ],
            [
                'id'  => 89,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Редактирование заказов',
                'description' => 'Возможность редактировать заказов',
                'parameter' => 'menu.main.orders.edit'
            ],
            [
                'id'  => 90,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'АТС',
                'description' => 'АТС',
                'parameter' => 'menu.main.ats'
            ],
            [
                'id'  => 91,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Создание',
                'description' => 'Создание',
                'parameter' => 'menu.main.ats.create'
            ],
            [
                'id'  => 92,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Редактирование',
                'description' => 'Редактирование',
                'parameter' => 'menu.main.ats.edit'
            ],
            [
                'id'  => 93,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Редактирование привязки к компании.',
                'description' => 'Редактирование привязки к компании.',
                'parameter' => 'menu.main.ats.edit_to_company_binding'
            ],
            [
                'id'  => 94,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Редактирование привязки к АТС.',
                'description' => 'Редактирование привязки к АТС.',
                'parameter' => 'menu.main.ats.edit_to_ats_binding'
            ],
            [
                'id'  => 95,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Видимость групп дочерних компаний.',
                'description' => 'Видимость групп дочерних компаний.',
                'parameter' => 'menu.main.ats.child_company_group_view'
            ],
            [
                'id'  => 96,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Редактирование групп дочерних компаний.',
                'description' => 'Редактирование групп дочерних компаний.',
                'parameter' => 'menu.main.ats.child_company_group_edit'
            ],
            [
                'id'  => 97,
                'parent_id' => 3,
                'entity_id' => 1,
                'name'  =>'Справочники.Отправители',
                'description' =>'Справочники.Отправители',
                'parameter'  => 'menu.main.dictionaries.senders'
            ],
            [
                'id'  => 98,
                'parent_id' => 97,
                'entity_id' => 1,
                'name'  =>'Просмотр - Справочники.Отправители',
                'description' =>'Просмотр - Справочники.Отправители',
                'parameter'  => 'menu.main.dictionaries.senders.view'
            ],
            [
                'id'  => 99,
                'parent_id' => 97,
                'entity_id' => 1,
                'name'  =>'Редактирование - Справочники.Отправители',
                'description' =>'Редактирование - Справочники.Отправители',
                'parameter'  => 'menu.main.dictionaries.senders.edit'
            ],
            [
                'id'  => 100,
                'parent_id' => 97,
                'entity_id' => 1,
                'name'  =>'Создание - Справочники.Отправители',
                'description' =>'Создание - Справочники.Отправители',
                'parameter'  => 'menu.main.dictionaries.senders.create'
            ],
            [
                'id'  => 101,
                'parent_id' => 97,
                'entity_id' => 1,
                'name'  =>'Редактирование отправителей дочерних компаний - Справочники.Отправители',
                'description' =>'Редактирование отправителей дочерних компаний - Справочники.Отправители',
                'parameter'  => 'menu.main.dictionaries.senders.child_company_senders_edit'
            ],
            [
                'id'  => 102,
                'parent_id' => 90,
                'entity_id' => 1,
                'name'  =>'АТС.Транки',
                'description' =>'АТС.Транки',
                'parameter'  => 'menu.main.ats.trunks'
            ],
            [
                'id'  => 103,
                'parent_id' => 102,
                'entity_id' => 1,
                'name'  =>'Просмотр - АТС.Транки',
                'description' =>'Просмотр - АТС.Транки',
                'parameter'  => 'menu.main.ats.trunks.view'
            ],
            [
                'id'  => 104,
                'parent_id' => 102,
                'entity_id' => 1,
                'name'  =>'Создание - АТС.Транки',
                'description' =>'Создание - АТС.Транки',
                'parameter'  => 'menu.main.ats.trunks.create'
            ],
            [
                'id'  => 105,
                'parent_id' => 102,
                'entity_id' => 1,
                'name'  =>'Редактирование - АТС.Транки',
                'description' =>'Редактирование - АТС.Транки',
                'parameter'  => 'menu.main.ats.trunks.edit'
            ],
            [
                'id'  => 106,
                'parent_id' => 102,
                'entity_id' => 1,
                'name'  =>'Просмотр дочерних - АТС.Транки',
                'description' =>'Просмотр дочерних - АТС.Транки',
                'parameter'  => 'menu.main.ats.trunks.child_view'
            ],
            [
                'id'  => 107,
                'parent_id' => 102,
                'entity_id' => 1,
                'name'  =>'Редактирование дочерних - АТС.Транки',
                'description' =>'Редактирование дочерних - АТС.Транки',
                'parameter'  => 'menu.main.ats.trunks.child_edit'
            ],
            [
                'id'  => 108,
                'parent_id' => 1,
                'entity_id' => 1,
                'name'  =>'Логи',
                'description' =>'Логи',
                'parameter'  => 'menu.main.logs'
            ],
            [
                'id'  => 109,
                'parent_id' => 108,
                'entity_id' => 1,
                'name'  =>'Логи',
                'description' =>'Логи',
                'parameter'  => 'menu.main.logs.users_visits'
            ],
            [
                'id'  => 110,
                'parent_id' => 109,
                'entity_id' => 1,
                'name'  =>'Логи посещения пользователей',
                'description' =>'Логи посещения пользователей',
                'parameter'  => 'menu.main.logs.users_visits.view'
            ],
            [
                'id'  => 111,
                'parent_id' => 109,
                'entity_id' => 1,
                'name'  =>'Просмотр пользователей дочерних организаций - Логи.Посещения пользователей',
                'description' =>'Просмотр пользователей дочерних организаций - Логи.Посещения пользователей',
                'parameter'  => 'menu.main.logs.users_visits.child_company_users_view'
            ],
            [
                'id'  => 112,
                'parent_id' => 90,
                'entity_id' => 1,
                'name'  =>'Логи звонков',
                'description' =>'Логи звонков',
                'parameter'  => 'menu.main.ats.logs'
            ],
            [
                'id'  => 113,
                'parent_id' => 67,
                'entity_id' => 1,
                'name' => 'Редактировать транки других доступных компаний.',
                'description' => 'Транки - Редактировать транки других доступных компаний.',
                'parameter' => 'menu.main.tranks.edit_other_company_tranks',
            ],
            [
                'id' => 114,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'АТС. Пользователи',
                'description' => 'АТС. Пользователи',
                'parameter' => 'menu.main.ats.users',
            ],
            [
                'id' => 115,
                'parent_id' => 114,
                'entity_id' => 1,
                'name' => 'Создание - АТС. Пользователи',
                'description' => 'Создание пользователей АТС',
                'parameter' => 'menu.main.ats.users.create',
            ],
            [
                'id' => 116,
                'parent_id' => 114,
                'entity_id' => 1,
                'name' => 'Просмотр - АТС. Пользователи',
                'description' => 'Просмотр пользователей АТС',
                'parameter' => 'menu.main.ats.users.view',
            ],
            [
                'id' => 117,
                'parent_id' => 114,
                'entity_id' => 1,
                'name' => 'Редактирование - АТС. Пользователи',
                'description' => 'Редактирование пользователей АТС',
                'parameter' => 'menu.main.ats.users.edit',
            ],
            [
                'id' => 118,
                'parent_id' => 114,
                'entity_id' => 1,
                'name' => 'Удаление - АТС. Пользователи',
                'description' => 'Удаление пользователей АТС',
                'parameter' => 'menu.main.ats.users.delete',
            ],
            [
                'id' => 119,
                'parent_id' => 114,
                'entity_id' => 1,
                'name' => 'Просмотр дочерних - АТС. Пользователи',
                'description' => 'Просмотр пользователей АТС дочерних групп',
                'parameter' => 'menu.main.ats.users.child_view',
            ],
            [
                'id' => 120,
                'parent_id' => 114,
                'entity_id' => 1,
                'name' => 'Редактирование дочерних - АТС. Пользователи',
                'description' => 'Редактирование пользователей АТС дочерних групп',
                'parameter' => 'menu.main.ats.users.child_edit',
            ],
            [
                'id'  => 121,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Просмотр групп АТС',
                'description' => 'АТС - Просмотр групп АТС.',
                'parameter' => 'menu.main.ats.view_groups',
            ],
            [
                'id'  => 122,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Провайдеры связи',
                'description' => 'Провайдеры связи.',
                'parameter' => 'menu.main.providers',
            ],
            [
                'id'  => 123,
                'parent_id' => 122,
                'entity_id' => 1,
                'name' => 'Просмотр',
                'description' => 'Провайдеры связи - Просмотр.',
                'parameter' => 'menu.main.providers.view',
            ],
            [
                'id'  => 124,
                'parent_id' => 122,
                'entity_id' => 1,
                'name' => 'Создание',
                'description' => 'Провайдеры связи - Создание.',
                'parameter' => 'menu.main.providers.create',
            ],
            [
                'id'  => 125,
                'parent_id' => 122,
                'entity_id' => 1,
                'name' => 'Редактирование',
                'description' => 'Провайдеры связи - Редактирование.',
                'parameter' => 'menu.main.providers.edit',
            ],
            [
                'id'  => 126,
                'parent_id' => 122,
                'entity_id' => 1,
                'name' => 'Удаление',
                'description' => 'Провайдеры связи - Удаление.',
                'parameter' => 'menu.main.providers.delete',
            ],
            // [ Перенесен в раздел заказов
            //     'id'  => 127,
            //     'parent_id' => 24,
            //     'entity_id' => 1,
            //     'name' => 'Возможность отправлять СМС',
            //     'description' => 'Возможность отправлять СМС',
            //     'parameter' => 'menu.main.dictionaries.sms.can_send',
            // ],
            [
                'id'  => 128,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Исходящие маршруты',
                'description' => 'АТС - Исходящие маршруты.',
                'parameter' => 'menu.main.ats.out_routes',
            ],
            [
                'id'  => 129,
                'parent_id' => 128,
                'entity_id' => 1,
                'name' => 'Просмотр',
                'description' => 'Исходящие маршруты - Просмотр',
                'parameter' => 'menu.main.ats.out_routes.view',
            ],
            [
                'id'  => 130,
                'parent_id' => 128,
                'entity_id' => 1,
                'name' => 'Создание',
                'description' => 'Исходящие маршруты - Создание',
                'parameter' => 'menu.main.ats.out_routes.create',
            ],
            [
                'id'  => 131,
                'parent_id' => 128,
                'entity_id' => 1,
                'name' => 'Редактирование',
                'description' => 'Исходящие маршруты - Редактирование',
                'parameter' => 'menu.main.ats.out_routes.edit',
            ],
            [
                'id'  => 132,
                'parent_id' => 128,
                'entity_id' => 1,
                'name' => 'Удаление',
                'description' => 'Исходящие маршруты - Удаление',
                'parameter' => 'menu.main.ats.out_routes.delete',
            ],
            [
                'id' => 133,
                'parent_id' => 114,
                'entity_id' => 1,
                'name' => 'Создание независимого - АТС. Пользователи',
                'description' => 'Создание независимых пользователей АТС',
                'parameter' => 'menu.main.ats.users.create_independent',
            ],
            [
                'id' => 134,
                'parent_id' => 114,
                'entity_id' => 1,
                'name' => 'Создание приватного - АТС. Пользователи',
                'description' => 'Создание приватных пользователей АТС',
                'parameter' => 'menu.main.ats.users.create_privat',
            ],
            [
                'id'  => 135,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'АТС. Очереди',
                'description' => 'АТС. Очереди',
                'parameter' => 'menu.main.ats.queues',
            ],
            [
                'id'  => 136,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Просмотр',
                'description' => 'АТС. Очереди - Просмотр',
                'parameter' => 'menu.main.ats.queues.view',
            ],
            [
                'id'  => 137,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Создание входящих очередей',
                'description' => 'АТС. Очереди - Создание входящих очередей',
                'parameter' => 'menu.main.ats.queues.create_in',
            ],
            [
                'id'  => 138,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Создание очередей автодозвона',
                'description' => 'АТС. Очереди - Создание очередей автодозвона',
                'parameter' => 'menu.main.ats.queues.create_auto',
            ],
            [
                'id'  => 139,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Редактирование входящих очередей',
                'description' => 'АТС. Очереди - Редактирование входящих очередей',
                'parameter' => 'menu.main.ats.queues.edit_in',
            ],
            [
                'id'  => 140,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Редактирование очередей автодозвона',
                'description' => 'АТС. Очереди - Редактирование очередей автодозвона',
                'parameter' => 'menu.main.ats.queues.edit_auto',
            ],
            [
                'id'  => 141,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Удаление',
                'description' => 'АТС. Очереди - Удаление',
                'parameter' => 'menu.main.ats.queues.delete',
            ],
            [
                'id'  => 142,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Редактирование спец. настроек',
                'description' => 'АТС. Очереди - Редактирование спец. настроек',
                'parameter' => 'menu.main.ats.queues.edit_options',
            ],
            [
                'id' => 143,
                'parent_id' => 84,
                'entity_id' => 1,
                'name' => 'Шаблоны СМС',
                'description' => 'Шаблоны СМС',
                'parameter' => 'menu.main.dictionaries.sms.sms_templates'
            ],
            [
                'id' => 144,
                'parent_id' => 143,
                'entity_id' => 1,
                'name' => 'Шаблоны СМС - Доступ на создание',
                'description' => 'Доступ на создание',
                'parameter' => 'menu.main.dictionaries.sms.sms_templates.create'
            ],
            [
                'id' => 145,
                'parent_id' => 143,
                'entity_id' => 1,
                'name' => 'Шаблоны СМС - Доступ на редактирование',
                'description' => 'Доступ на редактирование',
                'parameter' => 'menu.main.dictionaries.sms.sms_templates.edit'
            ],
            [
                'id' => 146,
                'parent_id' => 143,
                'entity_id' => 1,
                'name' => 'Шаблоны СМС - Доступ на просмотр чужих',
                'description' => 'Доступ на просмотр чужих',
                'parameter' => 'menu.main.dictionaries.sms.sms_templates.view_other'
            ],
            [
                'id' => 147,
                'parent_id' => 143,
                'entity_id' => 1,
                'name' => 'Шаблоны СМС - Доступ на редактирование чужих',
                'description' => 'Доступ на редактирование чужих',
                'parameter' => 'menu.main.dictionaries.sms.sms_templates.edit_other'
            ],
            [
                'id'  => 148,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Просмотр чужих',
                'description' => 'АТС. Очереди - Просмотр чужих',
                'parameter' => 'menu.main.ats.queues.view_other',
            ],
            [
                'id'  => 149,
                'parent_id' => 135,
                'entity_id' => 1,
                'name' => 'Редактирование чужих',
                'description' => 'АТС. Очереди - Редактирование чужих',
                'parameter' => 'menu.main.ats.queues.edit_other',
            ],
            [
                'id'  => 150,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'АТС. Мониторинг',
                'description' => 'Мониторинг очередей автодозвона',
                'parameter' => 'menu.main.ats.monitoring',
            ],
            [
                'id'  => 151,
                'parent_id' => 150,
                'entity_id' => 1,
                'name' => 'Просмотр',
                'description' => 'АТС. Мониторинг - Просмотр',
                'parameter' => 'menu.main.ats.monitoring.view',
            ],
            [
                'id'  => 152,
                'parent_id' => 150,
                'entity_id' => 1,
                'name' => 'Просмотр отставаний',
                'description' => 'АТС. Мониторинг - Просмотр отставаний',
                'parameter' => 'menu.main.ats.monitoring.view_quench',
            ],
            [
                'id'  => 153,
                'parent_id' => 90,
                'entity_id' => 1,
                'name' => 'Просмотр',
                'description' => 'Просмотр серверов АТС',
                'parameter' => 'menu.main.ats.view',
            ],
            [
                'id'  => 154,
                'parent_id' => 24,
                'entity_id' => 1,
                'name' => 'Просмотр скрытых типов доставки',
                'description' => 'Просмотр скрытых типов доставки',
                'parameter' => 'menu.main.orders.can_view_hidden_delivery_type',
            ],
            [
                'id' => 155,
                'parent_id' => 1,
                'entity_id' => 1,
                'name' => 'Оптовичок',
                'description' => 'Доступ к разделу оптовичок',
                'parameter' => 'menu.main.optovichok'
            ],
            [
                'id' => 156,
                'parent_id' => 155,
                'entity_id' => 1,
                'name' => 'Создание клиента',
                'description' => 'Создание клиента',
                'parameter' => 'menu.main.optovichok.create'
            ],
            [
                'id' => 157,
                'parent_id' => 155,
                'entity_id' => 1,
                'name' => 'Обновление клиента',
                'description' => 'Обновление клиента',
                'parameter' => 'menu.main.optovichok.update'
            ],
            [
                'id' => 158,
                'parent_id' => 155,
                'entity_id' => 1,
                'name' => 'Удаление клиента',
                'description' => 'Удаление клиента',
                'parameter' => 'menu.main.optovichok.delete'
            ],
            [
                'id' => 159,
                'parent_id' => 155,
                'entity_id' => 1,
                'name' => 'Просмотр клиента',
                'description' => 'Просмотр клиента',
                'parameter' => 'menu.main.optovichok.view'
            ]
        ];

        foreach ($data as $item) {
            try {
                // $repo->create($item);
                $entity_param = EntityParam::create($item);

            } catch (Exception $e) {
                echo 'Выброшено исключение: ',  $e->getMessage(), "\n";
            }
        }
        
        $max    = DB::table('entity_params')->max('id') + 1;
        DB::statement('ALTER SEQUENCE entity_params_id_seq RESTART WITH ' . $max . ';');
    }
}
