<?php

use Illuminate\Database\Seeder;
use App\Repositories\GeoRepository;

class GeosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $repo    = resolve(GeoRepository::class);

        $data = [       

            ['mask'=>'+247',
             'code'=>'AC',
             'name_en'=>'Ascension',     
             'name_ru'=>'Остров Вознесения',
            ],

            ['mask'=>'+376',
             'code'=>'AD',
             'name_en'=>'Andorra',   
             'name_ru'=>'Андорра',
            ],            

            ['mask'=>'+971',
             'code'=>'AE',
             'name_en'=>'United Arab Emirates',  
             'name_ru'=>'Объединенные Арабские Эмираты',
            ],

            ['mask'=>'+93',
             'code'=>'AF',
             'name_en'=>'Afghanistan',   
             'name_ru'=>'Афганистан',
            ],

            ['mask'=>'+1268',
             'code'=>'AG',
             'name_en'=>'Antigua & Barbuda',     
             'name_ru'=>'Антигуа и Барбуда',
            ],

            ['mask'=>'+1264',
             'code'=>'AI',
             'name_en'=>'Anguilla',  
             'name_ru'=>'Ангилья',
            ],

            ['mask'=>'+355',
             'code'=>'AL',
             'name_en'=>'Albania',   
             'name_ru'=>'Албания',
            ],

            ['mask'=>'+374',
             'code'=>'AM',
             'name_en'=>'Armenia',   
             'name_ru'=>'Армения',
            ],            

            ['mask'=>'+5999',
             'code'=>'AN',
             'name_en'=>'Netherlands Antilles',  
             'name_ru'=>'Нидерландские Антильские острова',
            ],

            ['mask'=>'+244',
             'code'=>'AO',
             'name_en'=>'Angola',    
             'name_ru'=>'Ангола',
            ],

            ['mask'=>'+6721',
             'code'=>'AQ',
             'name_en'=>'Australian bases in Antarctica',    
             'name_ru'=>'Австралийская антарктическая база',
            ],

            ['mask'=>'+54',
             'code'=>'AR',
             'name_en'=>'Argentina',     
             'name_ru'=>'Аргентина',
            ],

            ['mask'=>'+1684',
             'code'=>'AS',
             'name_en'=>'American Samoa',    
             'name_ru'=>'Американское Самоа',
            ],

            ['mask'=>'+43',
             'code'=>'AT',
             'name_en'=>'Austria',   
             'name_ru'=>'Австрия',
            ],

            ['mask'=>'+61',
             'code'=>'AU',
             'name_en'=>'Australia',     
             'name_ru'=>'Австралия',
            ],

            ['mask'=>'+297',
             'code'=>'AW',
             'name_en'=>'Aruba',     
             'name_ru'=>'Аруба',
            ],

            ['mask'=>'+994',
             'code'=>'AZ',
             'name_en'=>'Azerbaijan',    
             'name_ru'=>'Азербайджан',
            ],

            ['mask'=>'+387',
             'code'=>'BA',
             'name_en'=>'Bosnia and Herzegovina',    
             'name_ru'=>'Босния и Герцеговина',
            ],            

            ['mask'=>'+1246',
             'code'=>'BB',
             'name_en'=>'Barbados',  
             'name_ru'=>'Барбадос',
            ],

            ['mask'=>'+880',
             'code'=>'BD',
             'name_en'=>'Bangladesh',    
             'name_ru'=>'Бангладеш',
            ],

            ['mask'=>'+32',
             'code'=>'BE',
             'name_en'=>'Belgium',   
             'name_ru'=>'Бельгия',
            ],

            ['mask'=>'+226',
             'code'=>'BF',
             'name_en'=>'Burkina Faso',  
             'name_ru'=>'Буркина Фасо',
            ],

            ['mask'=>'+359',
             'code'=>'BG',
             'name_en'=>'Bulgaria',  
             'name_ru'=>'Болгария',
            ],

            ['mask'=>'+973',
             'code'=>'BH',
             'name_en'=>'Bahrain',   
             'name_ru'=>'Бахрейн',
            ],

            ['mask'=>'+257',
             'code'=>'BI',
             'name_en'=>'Burundi',   
             'name_ru'=>'Бурунди',
            ],

            ['mask'=>'+229',
             'code'=>'BJ',
             'name_en'=>'Benin',     
             'name_ru'=>'Бенин',
            ],

            ['mask'=>'+1441',
             'code'=>'BM',
             'name_en'=>'Bermuda',   
             'name_ru'=>'Бермудские острова',
            ],

            ['mask'=>'+673',
             'code'=>'BN',
             'name_en'=>'Brunei Darussalam',     
             'name_ru'=>'БрунейДаруссалам',
            ],

            ['mask'=>'+591',
             'code'=>'BO',
             'name_en'=>'Bolivia',   
             'name_ru'=>'Боливия',
            ],

            ['mask'=>'+55',
             'code'=>'BR',
             'name_en'=>'Brazil',    
             'name_ru'=>'Бразилия',
            ],            

            ['mask'=>'+1242',
             'code'=>'BS',
             'name_en'=>'Bahamas',   
             'name_ru'=>'Багамские Острова',
            ],            

            ['mask'=>'+975',
             'code'=>'BT',
             'name_en'=>'Bhutan',    
             'name_ru'=>'Бутан',
            ],

            ['mask'=>'+267',
             'code'=>'BW',
             'name_en'=>'Botswana',  
             'name_ru'=>'Ботсвана',
            ],

            ['mask'=>'+375',
             'code'=>'BY',
             'name_en'=>'Belarus',   
             'name_ru'=>'Беларусь Белоруссия',
            ],

            ['mask'=>'+501',
             'code'=>'BZ',
             'name_en'=>'Belize',    
             'name_ru'=>'Белиз',
            ],

            ['mask'=>'+243',
             'code'=>'CD',
             'name_en'=>'Dem. Rep. Congo',   
             'name_ru'=>'Дем. Респ. Конго Киншаса',
            ],

            ['mask'=>'+236',
             'code'=>'CF',
             'name_en'=>'Central African Republic',  
             'name_ru'=>'Центральноафриканская Республика',
            ],

            ['mask'=>'+242',
             'code'=>'CG',
             'name_en'=>'Congo Brazzaville',     
             'name_ru'=>'Конго Браззавиль',
            ],

            ['mask'=>'+41',
             'code'=>'CH',
             'name_en'=>'Switzerland',   
             'name_ru'=>'Швейцария',
            ],

            ['mask'=>'+225',
             'code'=>'CI',
             'name_en'=>'Cote d’Ivoire Ivory Coast',     
             'name_ru'=>'Котд’Ивуар',
            ],

            ['mask'=>'+682',
             'code'=>'CK',
             'name_en'=>'Cook Islands',  
             'name_ru'=>'Острова Кука',
            ],

            ['mask'=>'+56',
             'code'=>'CL',
             'name_en'=>'Chile',     
             'name_ru'=>'Чили',
            ],

            ['mask'=>'+237',
             'code'=>'CM',
             'name_en'=>'Cameroon',  
             'name_ru'=>'Камерун',
            ],            

            ['mask'=>'+86',
             'code'=>'CN',
             'name_en'=>'China PRC',     
             'name_ru'=>'Китайская Н.Р.',
            ],

            ['mask'=>'+57',
             'code'=>'CO',
             'name_en'=>'Colombia',  
             'name_ru'=>'Колумбия',
            ],

            ['mask'=>'+506',
             'code'=>'CR',
             'name_en'=>'Costa Rica',    
             'name_ru'=>'КостаРика',
            ],

            ['mask'=>'+53',
             'code'=>'CU',
             'name_en'=>'Cuba',  
             'name_ru'=>'Куба',
            ],

            ['mask'=>'+238',
             'code'=>'CV',
             'name_en'=>'Cape Verde',    
             'name_ru'=>'КабоВерде',
            ],

            ['mask'=>'+599',
             'code'=>'CW',
             'name_en'=>'Curacao',   
             'name_ru'=>'Кюрасао',
            ],

            ['mask'=>'+357',
             'code'=>'CY',
             'name_en'=>'Cyprus',    
             'name_ru'=>'Кипр',
            ],

            ['mask'=>'+420',
             'code'=>'CZ',
             'name_en'=>'Czech Republic',    
             'name_ru'=>'Чехия',
            ],            

            ['mask'=>'+49',
             'code'=>'DE',
             'name_en'=>'Germany',   
             'name_ru'=>'Германия',
            ],

            ['mask'=>'+253',
             'code'=>'DJ',
             'name_en'=>'Djibouti',  
             'name_ru'=>'Джибути',
            ],

            ['mask'=>'+45',
             'code'=>'DK',
             'name_en'=>'Denmark',   
             'name_ru'=>'Дания',
            ],

            ['mask'=>'+1767',
             'code'=>'DM',
             'name_en'=>'Dominica',  
             'name_ru'=>'Доминика',
            ],            

            ['mask'=>'+1849',
             'code'=>'DO',
             'name_en'=>'Dominican Republic',    
             'name_ru'=>'Доминиканская Республика',
            ],

            ['mask'=>'+213',
             'code'=>'DZ',
             'name_en'=>'Algeria',   
             'name_ru'=>'Алжир',
            ],

            ['mask'=>'+593',
             'code'=>'EC',
             'name_en'=>'Ecuador',   
             'name_ru'=>'Эквадор',
            ],            

            ['mask'=>'+372',
             'code'=>'EE',
             'name_en'=>'Estonia',   
             'name_ru'=>'Эстония',
            ],

            ['mask'=>'+20',
             'code'=>'EG',
             'name_en'=>'Egypt',     
             'name_ru'=>'Египет',
            ],

            ['mask'=>'+291',
             'code'=>'ER',
             'name_en'=>'Eritrea',   
             'name_ru'=>'Эритрея',
            ],

            ['mask'=>'+34',
             'code'=>'ES',
             'name_en'=>'Spain',     
             'name_ru'=>'Испания',
            ],

            ['mask'=>'+251',
             'code'=>'ET',
             'name_en'=>'Ethiopia',  
             'name_ru'=>'Эфиопия',
            ],

            ['mask'=>'+358',
             'code'=>'FI',
             'name_en'=>'Finland',   
             'name_ru'=>'Финляндия',
            ],

            ['mask'=>'+679',
             'code'=>'FJ',
             'name_en'=>'Fiji',  
             'name_ru'=>'Фиджи',
            ],

            ['mask'=>'+500',
             'code'=>'FK',
             'name_en'=>'Falkland Islands',  
             'name_ru'=>'Фолклендские острова',
            ],

            ['mask'=>'+691',
             'code'=>'FM',
             'name_en'=>'F.S. Micronesia',   
             'name_ru'=>'Ф.Ш. Микронезии',
            ],

            ['mask'=>'+298',
             'code'=>'FO',
             'name_en'=>'Faroe Islands',     
             'name_ru'=>'Фарерские острова',
            ],

            ['mask'=>'+262',
             'code'=>'FR',
             'name_en'=>'Mayotte',   
             'name_ru'=>'Майотта',
            ],

            ['mask'=>'+33',
             'code'=>'FR',
             'name_en'=>'France',    
             'name_ru'=>'Франция',
            ],

            ['mask'=>'+508',
             'code'=>'FR',
             'name_en'=>'St Pierre & Miquelon',  
             'name_ru'=>'СенПьер и Микелон',
            ],

            ['mask'=>'+590',
             'code'=>'FR',
             'name_en'=>'Guadeloupe',    
             'name_ru'=>'Гваделупа',
            ],

            ['mask'=>'+241',
             'code'=>'GA',
             'name_en'=>'Gabon',     
             'name_ru'=>'Габон',
            ],

            ['mask'=>'+1473',
             'code'=>'GD',
             'name_en'=>'Grenada',   
             'name_ru'=>'Гренада',
            ],

            ['mask'=>'+995',
             'code'=>'GE',
             'name_en'=>'Rep. of Georgia',   
             'name_ru'=>'Грузия',
            ],

            ['mask'=>'+594',
             'code'=>'GF',
             'name_en'=>'Guiana French',     
             'name_ru'=>'Фр. Гвиана',
            ],

            ['mask'=>'+233',
             'code'=>'GH',
             'name_en'=>'Ghana',     
             'name_ru'=>'Гана',
            ],

            ['mask'=>'+350',
             'code'=>'GI',
             'name_en'=>'Gibraltar',     
             'name_ru'=>'Гибралтар',
            ],

            ['mask'=>'+299',
             'code'=>'GL',
             'name_en'=>'Greenland',     
             'name_ru'=>'Гренландия',
            ],

            ['mask'=>'+220',
             'code'=>'GM',
             'name_en'=>'Gambia',    
             'name_ru'=>'Гамбия',
            ],

            ['mask'=>'+224',
             'code'=>'GN',
             'name_en'=>'Guinea',    
             'name_ru'=>'Гвинея',
            ],

            ['mask'=>'+240',
             'code'=>'GQ',
             'name_en'=>'Equatorial Guinea',     
             'name_ru'=>'Экваториальная Гвинея',
            ],

            ['mask'=>'+30',
             'code'=>'GR',
             'name_en'=>'Greece',    
             'name_ru'=>'Греция',
            ],

            ['mask'=>'+502',
             'code'=>'GT',
             'name_en'=>'Guatemala',     
             'name_ru'=>'Гватемала',
            ],

            ['mask'=>'+1671',
             'code'=>'GU',
             'name_en'=>'Guam',  
             'name_ru'=>'Гуам',
            ],

            ['mask'=>'+245',
             'code'=>'GW',
             'name_en'=>'GuineaBissau',  
             'name_ru'=>'ГвинеяБисау',
            ],

            ['mask'=>'+592',
             'code'=>'GY',
             'name_en'=>'Guyana',    
             'name_ru'=>'Гайана',
            ],

            ['mask'=>'+852',
             'code'=>'HK',
             'name_en'=>'Hong Kong',     
             'name_ru'=>'Гонконг',
            ],

            ['mask'=>'+504',
             'code'=>'HN',
             'name_en'=>'Honduras',  
             'name_ru'=>'Гондурас',
            ],

            ['mask'=>'+385',
             'code'=>'HR',
             'name_en'=>'Croatia',   
             'name_ru'=>'Хорватия',
            ],

            ['mask'=>'+509',
             'code'=>'HT',
             'name_en'=>'Haiti',     
             'name_ru'=>'Гаити',
            ],

            ['mask'=>'+36',
             'code'=>'HU',
             'name_en'=>'Hungary',   
             'name_ru'=>'Венгрия',
            ],            

            ['mask'=>'+62',
             'code'=>'ID',
             'name_en'=>'Indonesia',     
             'name_ru'=>'Индонезия',
            ],            

            ['mask'=>'+353',
             'code'=>'IE',
             'name_en'=>'Ireland',   
             'name_ru'=>'Ирландия',
            ],

            ['mask'=>'+9725',
             'code'=>'IL',
             'name_en'=>'Israel',   
             'name_ru'=>'Израиль',
             ],

            ['mask'=>'+972',
             'code'=>'IL',
             'name_en'=>'Israel',    
             'name_ru'=>'Израиль',
            ],

            ['mask'=>'+91',
             'code'=>'IN',
             'name_en'=>'India',     
             'name_ru'=>'Индия',
            ],

            ['mask'=>'+246',
             'code'=>'IO',
             'name_en'=>'Diego Garcia',  
             'name_ru'=>'ДиегоГарсия',
            ],

            ['mask'=>'+964',
             'code'=>'IQ',
             'name_en'=>'Iraq',  
             'name_ru'=>'Ирак',
            ],

            ['mask'=>'+98',
             'code'=>'IR',
             'name_en'=>'Iran',  
             'name_ru'=>'Иран',
            ],

            ['mask'=>'+354',
             'code'=>'IS',
             'name_en'=>'Iceland',   
             'name_ru'=>'Исландия',
            ],

            ['mask'=>'+39',
             'code'=>'IT',
             'name_en'=>'Italy',     
             'name_ru'=>'Италия',
            ],

            ['mask'=>'+1876',
             'code'=>'JM',
             'name_en'=>'Jamaica',   
             'name_ru'=>'Ямайка',
            ],

            ['mask'=>'+962',
             'code'=>'JO',
             'name_en'=>'Jordan',    
             'name_ru'=>'Иордания',
            ],            

            ['mask'=>'+81',
             'code'=>'JP',
             'name_en'=>'Japan',     
             'name_ru'=>'Япония',
            ],

            ['mask'=>'+254',
             'code'=>'KE',
             'name_en'=>'Kenya',     
             'name_ru'=>'Кения',
            ],

            ['mask'=>'+996',
             'code'=>'KG',
             'name_en'=>'Kyrgyzstan',    
             'name_ru'=>'Киргизия',
            ],

            ['mask'=>'+855',
             'code'=>'KH',
             'name_en'=>'Cambodia',  
             'name_ru'=>'Камбоджа',
            ],

            ['mask'=>'+686',
             'code'=>'KI',
             'name_en'=>'Kiribati',  
             'name_ru'=>'Кирибати',
            ],

            ['mask'=>'+269',
             'code'=>'KM',
             'name_en'=>'Comoros',   
             'name_ru'=>'Коморы',
            ],

            ['mask'=>'+1869',
             'code'=>'KN',
             'name_en'=>'Saint Kitts & Nevis',   
             'name_ru'=>'СентКитс и Невис',
            ],                        

            ['mask'=>'+850',
             'code'=>'KP',
             'name_en'=>'DPR Korea North',   
             'name_ru'=>'Корейская НДР',
            ],

            ['mask'=>'+82',
             'code'=>'KR',
             'name_en'=>'Korea South',   
             'name_ru'=>'Респ. Корея',
            ],

            ['mask'=>'+965',
             'code'=>'KW',
             'name_en'=>'Kuwait',    
             'name_ru'=>'Кувейт',
            ],

            ['mask'=>'+1345',
             'code'=>'KY',
             'name_en'=>'Cayman Islands',    
             'name_ru'=>'Каймановы острова',
            ],            

            ['mask'=>'+77',
             'code'=>'KZ',
             'name_en'=>'Kazakhstan',    
             'name_ru'=>'Казахстан',
            ],            

            ['mask'=>'+856',
             'code'=>'LA',
             'name_en'=>'Laos',  
             'name_ru'=>'Лаос',
            ],

            ['mask'=>'+961',
             'code'=>'LB',
             'name_en'=>'Lebanon',  
             'name_ru'=>'Ливан',
            ],

            ['mask'=>'+961',
             'code'=>'LB',
             'name_en'=>'Lebanon',   
             'name_ru'=>'Ливан',
            ],

            ['mask'=>'+1758',
             'code'=>'LC',
             'name_en'=>'Saint Lucia',   
             'name_ru'=>'СентЛюсия',
            ],

            ['mask'=>'+423',
             'code'=>'LI',
             'name_en'=>'Liechtenstein',     
             'name_ru'=>'Лихтенштейн',
            ],

            ['mask'=>'+94',
             'code'=>'LK',
             'name_en'=>'Sri Lanka',     
             'name_ru'=>'ШриЛанка',
            ],

            ['mask'=>'+231',
             'code'=>'LR',
             'name_en'=>'Liberia',   
             'name_ru'=>'Либерия',
            ],

            ['mask'=>'+266',
             'code'=>'LS',
             'name_en'=>'Lesotho',   
             'name_ru'=>'Лесото',
            ],

            ['mask'=>'+370',
             'code'=>'LT',
             'name_en'=>'Lithuania',     
             'name_ru'=>'Литва',
            ],

            ['mask'=>'+352',
             'code'=>'LU',
             'name_en'=>'Luxembourg',    
             'name_ru'=>'Люксембург',
            ],

            ['mask'=>'+371',
             'code'=>'LV',
             'name_en'=>'Latvia',    
             'name_ru'=>'Латвия',
            ],

            ['mask'=>'+218',
             'code'=>'LY',
             'name_en'=>'Libya',     
             'name_ru'=>'Ливия',
            ],

            ['mask'=>'+21821',
             'code'=>'LY',
             'name_en'=>'Libya',     
             'name_ru'=>'Ливия',
            ],

            ['mask'=>'+212',
             'code'=>'MA',
             'name_en'=>'Morocco',   
             'name_ru'=>'Марокко',
            ],            

            ['mask'=>'+377',
             'code'=>'MC',
             'name_en'=>'Monaco',    
             'name_ru'=>'Монако',
            ],

            ['mask'=>'+373',
             'code'=>'MD',
             'name_en'=>'Moldova',   
             'name_ru'=>'Молдова',
            ],

            ['mask'=>'+382',
             'code'=>'ME',
             'name_en'=>'Montenegro',    
             'name_ru'=>'Черногория',
            ],

            ['mask'=>'+261',
             'code'=>'MG',
             'name_en'=>'Madagascar',    
             'name_ru'=>'Мадагаскар',
            ],

            ['mask'=>'+692',
             'code'=>'MH',
             'name_en'=>'Marshall Islands',  
             'name_ru'=>'Маршалловы Острова',
            ],

            ['mask'=>'+389',
             'code'=>'MK',
             'name_en'=>'Republic of Macedonia',     
             'name_ru'=>'Респ. Македония',
            ],

            ['mask'=>'+223',
             'code'=>'ML',
             'name_en'=>'Mali',  
             'name_ru'=>'Мали',
            ],            

            ['mask'=>'+95',
             'code'=>'MM',
             'name_en'=>'Burma Myanmar',     
             'name_ru'=>'Бирма Мьянма',
            ],

            ['mask'=>'+976',
             'code'=>'MN',
             'name_en'=>'Mongolia',  
             'name_ru'=>'Монголия',
            ],

            ['mask'=>'+853',
             'code'=>'MO',
             'name_en'=>'Macau',     
             'name_ru'=>'Макао',
            ],

            ['mask'=>'+1670',
             'code'=>'MP',
             'name_en'=>'Northern Mariana Islands',  
             'name_ru'=>'Северные Марианские острова Сайпан',
            ],

            ['mask'=>'+596',
             'code'=>'MQ',
             'name_en'=>'Martinique',    
             'name_ru'=>'Мартиника',
            ],

            ['mask'=>'+222',
             'code'=>'MR',
             'name_en'=>'Mauritania',    
             'name_ru'=>'Мавритания',
            ],

            ['mask'=>'+1664',
             'code'=>'MS',
             'name_en'=>'Montserrat',    
             'name_ru'=>'Монтсеррат',
            ],

            ['mask'=>'+356',
             'code'=>'MT',
             'name_en'=>'Malta',     
             'name_ru'=>'Мальта',
            ],

            ['mask'=>'+230',
             'code'=>'MU',
             'name_en'=>'Mauritius',     
             'name_ru'=>'Маврикий',
            ],

            ['mask'=>'+960',
             'code'=>'MV',
             'name_en'=>'Maldives',  
             'name_ru'=>'Мальдивские острова',
            ],            

            ['mask'=>'+265',
             'code'=>'MW',
             'name_en'=>'Malawi',    
             'name_ru'=>'Малави',
            ],            

            ['mask'=>'+52',
             'code'=>'MX',
             'name_en'=>'Mexico',    
             'name_ru'=>'Мексика',
            ],            

            ['mask'=>'+60',
             'code'=>'MY',
             'name_en'=>'Malaysia',  
             'name_ru'=>'Малайзия',
            ],

            ['mask'=>'+258',
             'code'=>'MZ',
             'name_en'=>'Mozambique',    
             'name_ru'=>'Мозамбик',
            ],

            ['mask'=>'+264',
             'code'=>'NA',
             'name_en'=>'Namibia',   
             'name_ru'=>'Намибия',
            ],

            ['mask'=>'+687',
             'code'=>'NC',
             'name_en'=>'New Caledonia',     
             'name_ru'=>'Новая Каледония',
            ],

            ['mask'=>'+227',
             'code'=>'NE',
             'name_en'=>'Niger',     
             'name_ru'=>'Нигер',
            ],

            ['mask'=>'+6723',
             'code'=>'NF',
             'name_en'=>'Norfolk Island',    
             'name_ru'=>'Норфолк остров',
            ],            

            ['mask'=>'+234',
             'code'=>'NG',
             'name_en'=>'Nigeria',  
             'name_ru'=>'Нигерия',
            ],

            ['mask'=>'+505',
             'code'=>'NI',
             'name_en'=>'Nicaragua',     
             'name_ru'=>'Никарагуа',
            ],

            ['mask'=>'+31',
             'code'=>'NL',
             'name_en'=>'Netherlands',   
             'name_ru'=>'Нидерланды',
            ],

            ['mask'=>'+47',
             'code'=>'NO',
             'name_en'=>'Norway',    
             'name_ru'=>'Норвегия',
            ],

            ['mask'=>'+977',
             'code'=>'NP',
             'name_en'=>'Nepal',     
             'name_ru'=>'Непал',
            ],

            ['mask'=>'+674',
             'code'=>'NR',
             'name_en'=>'Nauru',     
             'name_ru'=>'Науру',
            ],

            ['mask'=>'+683',
             'code'=>'NU',
             'name_en'=>'Niue',  
             'name_ru'=>'Ниуэ',
            ],            

            ['mask'=>'+64',
             'code'=>'NZ',
             'name_en'=>'New Zealand',   
             'name_ru'=>'Новая Зеландия',
            ],

            ['mask'=>'+968',
             'code'=>'OM',
             'name_en'=>'Oman',  
             'name_ru'=>'Оман',
            ],

            ['mask'=>'+507',
             'code'=>'PA',
             'name_en'=>'Panama',    
             'name_ru'=>'Панама',
            ],

            ['mask'=>'+51',
             'code'=>'PE',
             'name_en'=>'Peru',  
             'name_ru'=>'Перу',
            ],

            ['mask'=>'+689',
             'code'=>'PF',
             'name_en'=>'French Polynesia',  
             'name_ru'=>'Французская Полинезия Таити',
            ],

            ['mask'=>'+675',
             'code'=>'PG',
             'name_en'=>'Papua New Guinea',  
             'name_ru'=>'ПапуаНовая Гвинея',
            ],

            ['mask'=>'+63',
             'code'=>'PH',
             'name_en'=>'Philippines',   
             'name_ru'=>'Филиппины',
            ],

            ['mask'=>'+92',
             'code'=>'PK',
             'name_en'=>'Pakistan',  
             'name_ru'=>'Пакистан',
            ],

            ['mask'=>'+48',
             'code'=>'PL',
             'name_en'=>'Poland',    
             'name_ru'=>'Польша',
            ],

            ['mask'=>'+970',
             'code'=>'PS',
             'name_en'=>'Palestine',     
             'name_ru'=>'Палестина',
            ],

            ['mask'=>'+351',
             'code'=>'PT',
             'name_en'=>'Portugal',  
             'name_ru'=>'Португалия',
            ],

            ['mask'=>'+680',
             'code'=>'PW',
             'name_en'=>'Palau',     
             'name_ru'=>'Палау',
            ],

            ['mask'=>'+595',
             'code'=>'PY',
             'name_en'=>'Paraguay',  
             'name_ru'=>'Парагвай',
            ],

            ['mask'=>'+974',
             'code'=>'QA',
             'name_en'=>'Qatar',     
             'name_ru'=>'Катар',
            ],

            ['mask'=>'+262',
             'code'=>'RE',
             'name_en'=>'Reunion',   
             'name_ru'=>'Реюньон',
            ],

            ['mask'=>'+40',
             'code'=>'RO',
             'name_en'=>'Romania',   
             'name_ru'=>'Румыния',
            ],

            ['mask'=>'+381',
             'code'=>'RS',
             'name_en'=>'Serbia',    
             'name_ru'=>'Сербия',
            ],

            ['mask'=>'+7',
             'code'=>'RU',
             'name_en'=>'Russia',    
             'name_ru'=>'Россия',
            ],

            ['mask'=>'+250',
             'code'=>'RW',
             'name_en'=>'Rwanda',    
             'name_ru'=>'Руанда',
            ],            

            ['mask'=>'+966',
             'code'=>'SA',
             'name_en'=>'Saudi Arabia',  
             'name_ru'=>'Саудовская Аравия',
            ],         
            
            ['mask'=>'+677',
             'code'=>'SB',
             'name_en'=>'Solomon Islands',   
             'name_ru'=>'Соломоновы Острова',
            ],

            ['mask'=>'+248',
             'code'=>'SC',
             'name_en'=>'Seychelles',    
             'name_ru'=>'Сейшелы',
            ],

            ['mask'=>'+249',
             'code'=>'SD',
             'name_en'=>'Sudan',     
             'name_ru'=>'Судан',
            ],

            ['mask'=>'+46',
             'code'=>'SE',
             'name_en'=>'Sweden',    
             'name_ru'=>'Швеция',
            ],

            ['mask'=>'+65',
             'code'=>'SG',
             'name_en'=>'Singapore',     
             'name_ru'=>'Сингапур',
            ],

            ['mask'=>'+290',
             'code'=>'SH',
             'name_en'=>'Saint Helena',  
             'name_ru'=>'Остров Святой Елены',
            ],

            ['mask'=>'+290',
             'code'=>'SH',
             'name_en'=>'Tristan da Cunha',  
             'name_ru'=>'ТристандаКунья',
            ],

            ['mask'=>'+386',
             'code'=>'SI',
             'name_en'=>'Slovenia',  
             'name_ru'=>'Словения',
            ],

            ['mask'=>'+421',
             'code'=>'SK',
             'name_en'=>'Slovakia',  
             'name_ru'=>'Словакия',
            ],

            ['mask'=>'+232',
             'code'=>'SL',
             'name_en'=>'Sierra Leone',  
             'name_ru'=>'СьерраЛеоне',
            ],

            ['mask'=>'+378',
             'code'=>'SM',
             'name_en'=>'San Marino',    
             'name_ru'=>'СанМарино',
            ],

            ['mask'=>'+221',
             'code'=>'SN',
             'name_en'=>'Senegal',   
             'name_ru'=>'Сенегал',
            ],            

            ['mask'=>'+252',
             'code'=>'SO',
             'name_en'=>'Somalia',  
             'name_ru'=>'Сомали',
            ],            

            ['mask'=>'+597',
             'code'=>'SR',
             'name_en'=>'Suriname',  
             'name_ru'=>'Суринам',
            ],

            ['mask'=>'+211',
             'code'=>'SS',
             'name_en'=>'South Sudan',   
             'name_ru'=>'Южный Судан',
            ],

            ['mask'=>'+239',
             'code'=>'ST',
             'name_en'=>'Sao Tome and Principe',     
             'name_ru'=>'СанТоме и Принсипи',
            ],

            ['mask'=>'+503',
             'code'=>'SV',
             'name_en'=>'El Salvador',   
             'name_ru'=>'Сальвадор',
            ],

            ['mask'=>'+1721',
             'code'=>'SX',
             'name_en'=>'Sint Maarten',  
             'name_ru'=>'СинтМаартен',
            ],

            ['mask'=>'+963',
             'code'=>'SY',
             'name_en'=>'Syrian Arab Republic',  
             'name_ru'=>'Сирийская арабская республика',
            ],

            ['mask'=>'+268',
             'code'=>'SZ',
             'name_en'=>'Swaziland',     
             'name_ru'=>'Свазиленд',
            ],

            ['mask'=>'+1649',
             'code'=>'TC',
             'name_en'=>'Turks & Caicos',    
             'name_ru'=>'Тёркс и Кайкос',
            ],

            ['mask'=>'+235',
             'code'=>'TD',
             'name_en'=>'Chad',  
             'name_ru'=>'Чад',
            ],

            ['mask'=>'+228',
             'code'=>'TG',
             'name_en'=>'Togo',  
             'name_ru'=>'Того',
            ],            

            ['mask'=>'+66',
             'code'=>'TH',
             'name_en'=>'Thailand',  
             'name_ru'=>'Таиланд',
            ],

            ['mask'=>'+992',
             'code'=>'TJ',
             'name_en'=>'Tajikistan',    
             'name_ru'=>'Таджикистан',
            ],

            ['mask'=>'+690',
             'code'=>'TK',
             'name_en'=>'Tokelau',   
             'name_ru'=>'Токелау',
            ],

            ['mask'=>'+670',
             'code'=>'TL',
             'name_en'=>'East Timor',    
             'name_ru'=>'Восточный Тимор',
            ],            

            ['mask'=>'+993',
             'code'=>'TM',
             'name_en'=>'Turkmenistan',  
             'name_ru'=>'Туркменистан',
            ],

            ['mask'=>'+216',
             'code'=>'TN',
             'name_en'=>'Tunisia',   
             'name_ru'=>'Тунис',
            ],

            ['mask'=>'+676',
             'code'=>'TO',
             'name_en'=>'Tonga',     
             'name_ru'=>'Тонга',
            ],

            ['mask'=>'+90',
             'code'=>'TR',
             'name_en'=>'Turkey',    
             'name_ru'=>'Турция',
            ],

            ['mask'=>'+1868',
             'code'=>'TT',
             'name_en'=>'Trinidad & Tobago',     
             'name_ru'=>'Тринидад и Тобаго',
            ],

            ['mask'=>'+688',
             'code'=>'TV',
             'name_en'=>'Tuvalu',   
             'name_ru'=>'Тувалу',
            ],

            ['mask'=>'+886',
             'code'=>'TW',
             'name_en'=>'Taiwan',    
             'name_ru'=>'Тайвань',
            ],

            ['mask'=>'+255',
             'code'=>'TZ',
             'name_en'=>'Tanzania',  
             'name_ru'=>'Танзания',
            ],

            ['mask'=>'+380',
             'code'=>'UA',
             'name_en'=>'Ukraine',   
             'name_ru'=>'Украина',
            ],

            ['mask'=>'+256',
             'code'=>'UG',
             'name_en'=>'Uganda',    
             'name_ru'=>'Уганда',
            ],

            ['mask'=>'+44',
             'code'=>'UK',
             'name_en'=>'United Kingdom',    
             'name_ru'=>'Великобритания',
            ],

            ['mask'=>'+598',
             'code'=>'UY',
             'name_en'=>'Uruguay',   
             'name_ru'=>'Уругвай',
            ],

            ['mask'=>'+998',
             'code'=>'UZ',
             'name_en'=>'Uzbekistan',    
             'name_ru'=>'Узбекистан',
            ],

            ['mask'=>'+396698',
             'code'=>'VA',
             'name_en'=>'Vatican City',  
             'name_ru'=>'Ватикан',
            ],

            ['mask'=>'+1784',
             'code'=>'VC',
             'name_en'=>'Saint Vincent & the Grenadines',    
             'name_ru'=>'СентВинсент и Гренадины',
            ],

            ['mask'=>'+58',
             'code'=>'VE',
             'name_en'=>'Venezuela',     
             'name_ru'=>'Венесуэла',
            ],

            ['mask'=>'+1284',
             'code'=>'VG',
             'name_en'=>'British Virgin Islands',    
             'name_ru'=>'Британские Виргинские острова',
            ],

            ['mask'=>'+1340',
             'code'=>'VI',
             'name_en'=>'US Virgin Islands',     
             'name_ru'=>'Американские Виргинские острова',
            ],

            ['mask'=>'+84',
             'code'=>'VN',
             'name_en'=>'Vietnam',   
             'name_ru'=>'Вьетнам',
            ],            

            ['mask'=>'+678',
             'code'=>'VU',
             'name_en'=>'Vanuatu ',  
             'name_ru'=>'Вануату ',
            ],            

            ['mask'=>'+681',
             'code'=>'WF',
             'name_en'=>'Wallis and Futuna',     
             'name_ru'=>'Уоллис и Футуна',
            ],

            ['mask'=>'+685',
             'code'=>'WS',
             'name_en'=>'Samoa',     
             'name_ru'=>'Самоа',
            ],

            ['mask'=>'+967',
             'code'=>'YE',
             'name_en'=>'Yemen ',    
             'name_ru'=>'Йемен ',
            ],            

            ['mask'=>'+27',
             'code'=>'ZA',
             'name_en'=>'South Africa',  
             'name_ru'=>'ЮжноАфриканская Респ.',
            ],

            ['mask'=>'+260',
             'code'=>'ZM',
             'name_en'=>'Zambia',    
             'name_ru'=>'Замбия',
            ],

            ['mask'=>'+263',
             'code'=>'ZW',
             'name_en'=>'Zimbabwe',  
             'name_ru'=>'Зимбабве',
            ],

            ['mask'=>'+1',
             'code'=> 'US',  
             'name_en'=>'USA',   
             'name_ru'=>'США',
            ],

            ['mask'=>'+1',
             'code'=> 'CA',
             'name_en'=>'Canada',    
             'name_ru'=>'Канада',
             ],

            ['mask'=>'+11111',
             'code'=> 'WW',
             'name_en'=>'Worldwide',    
             'name_ru'=>'Worldwide',
             ]


];

        foreach ($data as $item) {
            $repo->create($item);
        }
    }
}
